global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ignite-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Ahora apunta directamente al nombre del servicio en el docker-compose
      - targets: ['ignite-app:8080']