# Identificación del proyecto
sonar.projectKey=ignite
sonar.projectName=Ignite
sonar.projectVersion=1.0

# Fuentes y tests
sonar.sources=src/main/java
sonar.tests=src/test/java

# Código binario y cobertura (CRUCIAL para que vea el % de éxito)
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml