# ==========================================
# CONFIGURACION DE LE CONEXION DE H2
# ==========================================

spring.datasource.url=jdbc:h2:file:./ignitedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# HABILITAR CONSOLA DE H2 PARA WEB
# ==========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# CONFIGURACION DEL JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACION DEL RATE LIMITER
# ==========================================
resilience4j.ratelimiter.instances.envioSolicitudes.limit-for-period=5
resilience4j.ratelimiter.instances.envioSolicitudes.limit-refresh-period=1m
resilience4j.ratelimiter.instances.envioSolicitudes.timeout-duration=0s

# ==========================================
# CONFIGURACION DEL ACTUADOR
# ==========================================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=Ignite

# ==========================================
# CONFIGURACION DE SEGURIDAD (JWT)
# ==========================================
api.security.token.secret=MiSecretoSuperSeguroIgnite2026
