# ==========================================
# Configuracion de la conexion a H2 (en memoria)
# ==========================================

spring.datasource.url=jdbc:h2:file:./ignitedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# Habilitar la consola de H2 para ver las tablas desde el navegador
# ==========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# Configuracion de JPA / Hibernate
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# Configuracion del rate limiter
# ==========================================
resilience4j.ratelimiter.instances.envioSolicitudes.limit-for-period=5
resilience4j.ratelimiter.instances.envioSolicitudes.limit-refresh-period=1m
resilience4j.ratelimiter.instances.envioSolicitudes.timeout-duration=0s

# ==========================================
# Configuracion del actuador
# ==========================================
# Exponemos las rutas de salud general y la ruta específica para Prometheus
management.endpoints.web.exposure.include=health,info,prometheus

# Habilitamos la exportación de datos en formato Prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

# (Opcional) Agrega etiquetas globales, como el nombre de tu app,
# muy útil si luego tienes múltiples microservicios
management.metrics.tags.application=Ignite

# ==========================================
# CONFIGURACIÓN DE SEGURIDAD (JWT)
# ==========================================
# Esta es la firma secreta del servidor. En producción, esto debe ser una variable de entorno muy compleja.
api.security.token.secret=MiSecretoSuperSeguroIgnite2026
